services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: twitter-backend
    ports:
      - "8081:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: twitter-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    restart: unless-stopped
