version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app  # mount local backend folder
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app  # mount local frontend folder
    depends_on:
      - backend
